version: "3"

networks:
  traefik-net:
    external: true

services:
  traefik-ingress:
    image: traefik:v2.3.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net

  frontend:
    image: ghcr.io/traefik-example/frontend:latest
    labels:
      - traefik.http.routers.back.rule=Host(`frontend.ldamore.com`)
      - traefik.port=3000
    networks:
      - traefik-net

  backend:
    image: ghcr.io/traefik-example/backend:latest
    labels:
      - traefik.http.routers.back.rule=Host(`backend.ldamore.com`)
      - traefik.port=6060
    networks:
      - traefik-net
